import {vectorHTML} from '../components/vector-lane.js';
import {renderStages,stageLabel} from '../components/relay-stage.js';
import {expectedIntermediates} from '../engine/answer-validator.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=(values,current)=>values.map(v=>`<option value="${v}" ${v===current?'selected':''}>${v}</option>`).join('');
const palette=['ewAdd','ewMultiply','square','scale','sum','mean','weightedSum','max','dot','noReduction'];
function inputName(q){return q.target==='losses'?'ℓ':q.target==='e'?'e':'x';}
function laneCalculator(q,session){const expected=expectedIntermediates(q);if(!expected.length)return '<p class="muted">This relay has no component-wise intermediate station.</p>';return expected.map((row,ri)=>`<fieldset><legend>Intermediate vector ${ri+1}</legend><div class="lane-inputs">${row.map((_,i)=>`<label>Lane ${i+1}<input inputmode="decimal" data-array="intermediates" data-row="${ri}" data-index="${i}" value="${esc(session.intermediates?.[ri]?.[i])}"></label>`).join('')}</div></fieldset>`).join('');}
function gradientTiles(q){const n=q.x.length,symbols=['0','1',`1/${n}`,'g',...q.x.map((_,i)=>`x${i+1}`),...(q.y||[]).map((_,i)=>`y${i+1}`),...q.x.map((_,i)=>`2x${i+1}`),...(q.w||[]).map((_,i)=>`w${i+1}`)];return [...new Set(symbols)].map(s=>`<button class="tile" data-tile="${s}">${s}</button>`).join('');}
function targetFormula(q){const v=inputName(q);return ({sum:`s = Σᵢ ${v}ᵢ`,mean:`m = (1/n) Σᵢ ${v}ᵢ`,'weighted-sum':'s = Σᵢ wᵢxᵢ',dot:'s = xᵀy = Σᵢ xᵢyᵢ','sum-squares':`s = Σᵢ ${v}ᵢ²`,'weighted-sum-squares':'s = Σᵢ wᵢxᵢ²',mse:`m = (1/n) Σᵢ ${v}ᵢ²`,max:`s = maxᵢ ${v}ᵢ`}[q.family]||'vector → scalar');}
function explanation(q){if(q.family==='max')return 'With a unique maximum, only the winning lane has local slope one; every other lane has local slope zero. A tie would be nondifferentiable.';if(q.family==='dot')return 'The product-vector Jacobian is diagonal. The sum row multiplies that diagonal, leaving the opposite operand as an ordered row; the upstream scalar then scales every entry.';if(q.family==='mean'||q.family==='mse')return 'The reduction sends a branch to every lane and contributes one 1/n factor. Local factors multiply with the incoming scalar gradient.';if(q.family.includes('squares'))return 'Each square contributes 2xᵢ on its own lane. The reduction preserves all structural paths and the upstream scalar multiplies each coefficient.';if(q.family==='weighted-sum')return 'Each input affects the scalar through its matching weight, so the numerator-layout derivative is the ordered weight row.';return 'A sum contracts the vector to a scalar without erasing dependencies. Reversing it sends local slope one to every input lane.';}
function axisChallenge(q,session){if(!q.axisChallenge)return '';const matrix=q.axisChallenge.matrix,task=q.axisChallenge.axis==='rows'?'produce one sum for each row':q.axisChallenge.axis==='columns'?'produce one sum for each column':'produce one global scalar sum';return `<section class="card axis-challenge"><span class="kicker">Matrix axis checkpoint</span><h2>Choose an explicit reduction axis</h2><p>For matrix [${matrix.map(row=>`[${row.join(', ')}]`).join(', ')}], ${task}.</p><div class="grid-3"><label>Axis<select data-field="axisChoice"><option value="">Choose</option><option value="rows" ${session.axisChoice==='rows'?'selected':''}>Across columns (one per row)</option><option value="columns" ${session.axisChoice==='columns'?'selected':''}>Across rows (one per column)</option><option value="all" ${session.axisChoice==='all'?'selected':''}>All entries</option></select></label><label>Output shape<select data-field="axisShape"><option value="">Choose</option>${['2×1',`1×${matrix[0].length}`,'scalar'].map(value=>`<option ${session.axisShape===value?'selected':''}>${value}</option>`).join('')}</select></label><label>Output value(s)<input data-field="axisOutput" value="${esc(session.axisOutput)}" placeholder="e.g. [3, 7]"></label></div></section>`;}
function comparisonChallenge(q,session){if(q.comparison!=='sum-mean')return '';return `<section class="card comparison-manifest"><span class="kicker">Direct comparison</span><h2>Compute both reductions on the same vector</h2><div class="grid-2"><div><h3>Sum</h3><label>Output<input data-field="comparisonSum" value="${esc(session.comparisonSum)}"></label><label>Gradient row<input data-field="comparisonSumGradient" value="${esc(session.comparisonSumGradient)}"></label></div><div><h3>Mean</h3><label>Output<input data-field="comparisonMean" value="${esc(session.comparisonMean)}"></label><label>Gradient row<input data-field="comparisonMeanGradient" value="${esc(session.comparisonMeanGradient)}"></label></div></div></section>`;}

export function relayView(level,q,session,feedback=''){
 const n=q.x.length,upstream=q.upstream??1,target=q.target||'x',mastery=session.roundType==='mastery',guided=session.roundType==='guided';
 const contrast=level.id===10?'<div class="card concept-contrast"><h2>Element-wise versus dot product</h2><p><strong>x ⊙ y:</strong> vector output, local Jacobian diag(y).</p><p><strong>xᵀy:</strong> x ⊙ y → product vector p → sum → scalar; [1 … 1]diag(y)=yᵀ.</p></div>':level.id===17?'<div class="card concept-contrast"><h2>Broadcasting versus reduction</h2><p>Broadcasting: scalar → n×1 vector, derivative orientation n×1.</p><p>Reduction: n×1 vector → scalar, derivative orientation 1×n.</p></div>':'';
 return `<section class="stack relay-workspace"><div class="topbar"><div><span class="badge">Level ${level.id} of 20 · ${esc(session.roundType||'guided')}</span><h1>${esc(level.title)}</h1><p class="muted">${esc(level.objective)}</p></div><button class="ghost" data-action="levels">Choose level</button></div>
 <div class="round-tabs" role="group" aria-label="Round type">${level.rounds.map(type=>`<button class="secondary" data-round="${type}" aria-pressed="${session.roundType===type}">${type}</button>`).join('')}</div>${contrast}${axisChallenge(q,session)}${comparisonChallenge(q,session)}
 <div class="grid-2"><div class="card"><h2>1. Inspect the relay card</h2><p>${esc(q.prompt)}</p><p class="equation" aria-label="Target computation"><strong>Target:</strong> ${targetFormula(q)}</p><p class="equation" aria-label="Input values"><strong>Given:</strong> ${inputName(q)} = [${q.x.join(', ')}]${q.family==='dot'?` and y = [${q.y.join(', ')}]`:''}${q.family.includes('weighted')?` and w = [${q.w.join(', ')}]`:''}</p><div class="pill-row"><span class="shape-badge badge">${inputName(q)}: ${n}×1 column</span>${q.family==='dot'?`<span class="shape-badge badge">y: ${n}×1 column</span>`:''}<span class="shape-badge badge">output: scalar</span></div><label>Differentiation target<select data-field="target">${q.family==='dot'?`<option ${target==='x'?'selected':''}>x</option><option ${target==='y'?'selected':''}>y</option>`:`<option selected value="${esc(target)}">${esc(target)}</option>`}</select></label></div>
 <div class="card"><h2>2. Build and order stages</h2><p class="muted">Choose ordered operations that implement the target formula.</p>${guided?'<p class="callout">Guided clue: lane-wise operations preserve the vector; a reduction is the stage that reaches the scalar finish.</p>':''}${q.repair?`<p class="repair-note"><strong>Repair round (${esc(q.repair.type)}):</strong> exactly one supplied checkpoint is faulty. Find and repair it.</p>`:''}<div class="stage-builder">${palette.map(s=>`<button class="stage-chip" data-stage="${s}">+ ${stageLabel(s)}</button>`).join('')}</div>${renderStages(session.stages,true)}</div></div>
 <div class="card"><h2>3. Carry the shape baton</h2><p class="text-alt">Your predicted flow: ${n}×1${session.shapes?.map(shape=>` → ${shape||'?'}`).join('')||' → ?'}</p><div class="shape-predictions">${session.stages.map((s,i)=>`<label>After ${stageLabel(s)}<select data-array="shapes" data-index="${i}"><option value="">Choose shape</option>${options([`${n}×1`,`1×${n}`,'scalar'],session.shapes?.[i])}</select></label>`).join('')||'<p>Add stages to predict their shapes.</p>'}</div><p class="muted">Track whether each station preserves lanes or reduces them.</p></div>
 <div class="relay-board" aria-label="Forward lane diagram">${vectorHTML(inputName(q),q.x)}${q.family==='dot'?vectorHTML('y',q.y):''}<div class="funnel-route"><span>Every lane remains structurally connected</span><span class="funnel" aria-hidden="true">${q.family==='max'?'max':'Σ'}</span><span class="finish">scalar s</span></div>${renderStages(session.stages)}<div class="backward"><strong>Backward direction ←</strong> upstream scalar <span class="runner">g = ${upstream}</span> branches to all ${n} lanes.</div></div>
 <div class="grid-2"><div class="card"><h2>4. Lane calculator</h2>${laneCalculator(q,session)}</div><div class="card"><h2>5. Reduction funnel</h2><label>Scalar result<input data-field="scalar" inputmode="decimal" value="${esc(session.scalar)}"></label><p class="muted">All component routes remain visible even when an evaluated derivative is zero.</p></div></div>
 <div class="grid-2"><div class="card"><h2>6. Local backward derivatives</h2><label>Derivative shape<select data-field="derivativeShape"><option value="">Choose shape</option>${options([`${n}×1`,`1×${n}`,'scalar',`${n}×${n}`],session.derivativeShape)}</select></label>${mastery?'':`<div class="tile-tray" aria-label="Derivative tiles">${gradientTiles(q)}</div>`}<label>Local derivative row<input data-field="localGradient" value="${esc(session.localGradient)}" aria-describedby="gradient-format"></label><p id="gradient-format" class="muted">Entries may be numeric or symbolic, such as 1/${n}, y1, 2x1, or g*y1.</p></div>
 <div class="card"><h2>7. Upstream gradient distributor</h2><div class="gradient-branches">${q.x.map((_,i)=>`<span><b>g</b> × local lane ${i+1}</span>`).join('')}</div><label>Final 1×${n} gradient row<input data-field="finalGradient" value="${esc(session.finalGradient)}"></label><p>Multiply along each path. Do not add g to a local derivative.</p></div></div>
 <div class="actions"><button data-action="check">Check complete relay</button>${mastery?'':'<button class="secondary" data-action="hint">Hint for current stage</button>'}<button class="ghost" data-action="new-practice">New seeded round</button></div>${session.hint?`<div class="card hint" role="note">${esc(session.hint)}</div>`:''}${feedback}${session.complete?`<section class="card explanation"><h2>Why this relay works</h2><p>${explanation(q)}</p></section>`:''}</section>`;
}
