const STEPS=[
 {title:'Load a vector',formula:'\\mathbf{x}=\\begin{bmatrix}2\\\\-1\\\\4\\end{bmatrix}',note:'Three runners enter in separate lanes.',question:'What is the input shape?',choices:['3×1','1×3','scalar'],answer:'3×1'},
 {title:'Enter the sum station',formula:'s=x_1+x_2+x_3',note:'A reduction combines all lane values.',question:'Which stage implements this formula?',choices:['Sum','Mean','No Reduction'],answer:'Sum'},
 {title:'Compute the scalar finish',formula:'s=2+(-1)+4',note:'The output is one scalar.',question:'What value reaches the finish?',choices:['5','[2,-1,4]','3'],answer:'5'},
 {title:'Inspect shape change',formula:'3\\times1\\rightarrow\\text{scalar}',note:'Reduction changes shape.',question:'Does a reduction preserve vector shape?',choices:['No','Yes'],answer:'No'},
 {title:'Predict gradient shape',formula:'\\frac{\\partial s}{\\partial\\mathbf{x}}\\in\\mathbb{R}^{1\\times3}',note:'Numerator layout gives a row vector.',question:'Choose the derivative shape.',choices:['1×3','3×1','3×3'],answer:'1×3'},
 {title:'Inspect one component',formula:'\\frac{\\partial s}{\\partial x_1}=1',note:'One lane changes the sum at slope one.',question:'What is the local slope on lane 1?',choices:['1','0','x₁'],answer:'1'},
 {title:'Assemble the gradient',formula:'\\frac{\\partial s}{\\partial\\mathbf{x}}=\\begin{bmatrix}1&1&1\\end{bmatrix}',note:'One partial derivative per component.',question:'Which orientation is correct?',choices:['[1, 1, 1] row','[1; 1; 1] column'],answer:'[1, 1, 1] row'},
 {title:'Send an incoming gradient',formula:'\\frac{\\partial L}{\\partial\\mathbf{x}}=g\\begin{bmatrix}1&1&1\\end{bmatrix}',note:'Every lane receives g.',question:'How does g combine with each local slope?',choices:['Multiply','Add'],answer:'Multiply'},
 {title:'Preview a dot product',formula:'\\mathbf{x}^T\\mathbf{y}=\\sum_i x_i y_i',note:'First multiply matching lanes, then sum.',question:'Choose the stage order.',choices:['Element-wise Multiply → Sum','Sum → Element-wise Multiply','Element-wise Multiply only'],answer:'Element-wise Multiply → Sum'}
];
export const STAGE_GUIDE=[
 {name:'Element-wise Add',inputs:'two equal-length vectors',operation:'Add matching entries: pᵢ = xᵢ + yᵢ',output:'vector',example:'[2, −1, 4] + [3, 2, −2] = [5, 1, 2]'},
 {name:'Element-wise Multiply',inputs:'two equal-length vectors',operation:'Multiply matching entries: pᵢ = xᵢyᵢ',output:'vector',example:'[2, −1, 4] ⊙ [3, 2, −2] = [6, −2, −8]'},
 {name:'Square',inputs:'one vector',operation:'Square every entry: pᵢ = xᵢ²',output:'vector',example:'[2, −1, 4] → [4, 1, 16]'},
 {name:'Scale',inputs:'one vector and one scalar',operation:'Multiply every entry by the scalar',output:'vector',example:'3[2, −1, 4] = [6, −3, 12]'},
 {name:'Sum',inputs:'one vector',operation:'Add every entry: s = Σᵢxᵢ',output:'scalar',example:'[2, −1, 4] → 2 − 1 + 4 = 5'},
 {name:'Mean',inputs:'one vector',operation:'Sum, then divide once by n',output:'scalar',example:'[2, −1, 5] → 6/3 = 2'},
 {name:'Weighted Sum',inputs:'one vector and matching weights',operation:'Multiply each lane by its weight, then add',output:'scalar',example:'[2, −1] with w=[3, 4] → 6 − 4 = 2'},
 {name:'Maximum',inputs:'one vector',operation:'Select the largest entry',output:'scalar',example:'[2, −1, 4] → 4'},
 {name:'Dot Product',inputs:'two equal-length vectors',operation:'Element-wise Multiply, then Sum',output:'scalar',example:'[2, −1]ᵀ[3, 4] → [6, −4] → 2'},
 {name:'No Reduction',inputs:'one vector',operation:'Leave every entry unchanged',output:'vector',example:'[2, −1, 4] → [2, −1, 4]'}
];
function stageGuide(open=false){return `<details class="card stage-guide" ${open?'open':''}><summary>Stage dictionary: what every operation means</summary><p class="callout"><strong>Level 1:</strong> choose <strong>Sum</strong>. Element-wise Add needs a second vector and still produces a vector; Sum combines one vector into the requested scalar.</p><div class="stage-guide-scroll"><table><caption class="sr-only">Definitions of all stages available in the Relay Stage Builder</caption><thead><tr><th scope="col">Stage</th><th scope="col">Required input</th><th scope="col">What it does</th><th scope="col">Output</th><th scope="col">Example</th></tr></thead><tbody>${STAGE_GUIDE.map(stage=>`<tr><th scope="row">${stage.name}</th><td>${stage.inputs}</td><td>${stage.operation}</td><td><span class="badge shape-badge">${stage.output}</span></td><td>${stage.example}</td></tr>`).join('')}</tbody></table></div></details>`;}
export function isTutorialAnswerCorrect(step,answer){return STEPS[step]?.answer===answer;}
export function tutorialView(step=0,completed=false,feedback=''){const item=STEPS[step];return `<section class="stack tutorial-stage"><div class="topbar"><div><span class="badge">Tutorial ${step+1}/9</span><h1>${item.title}</h1></div><button class="ghost" data-action="home">Exit</button></div><div class="card"><div class="math">\\[${item.formula}\\]</div><p>${item.note}</p><fieldset class="tutorial-question"><legend>${item.question}</legend><div class="choice-grid">${item.choices.map(choice=>`<button class="choice" data-tutorial-answer="${choice}" aria-pressed="${completed&&choice===item.answer}">${choice}</button>`).join('')}</div></fieldset>${feedback?`<p class="tutorial-feedback ${completed?'correct':'incorrect'}" role="status">${feedback}</p>`:''}</div>${stageGuide(step===1)}<div class="relay-board"><div class="lane"><div class="lane-label">Forward</div><div class="track"><span class="runner">many values</span><span class="arrow">→</span><span class="station">lane work</span><span class="arrow">→</span><span class="funnel">Σ</span><span class="arrow">→</span><span class="finish">scalar</span></div></div><div class="backward">Backward: one scalar sensitivity branches to every contributing lane.</div></div><div class="actions"><button class="secondary" data-action="prev-tutorial" ${step===0?'disabled':''}>Previous</button><button data-action="next-tutorial" ${completed?'':'disabled'}>${step===8?'Start game':'Next'}</button></div></section>`;}
