export const GAME_DATA = [
  { id: 'shape-sorter', order: '01', title: 'Shape Sorter', description: 'Read derivative shapes before calculating values.', difficulty: 'Foundation', icon: '◇', requiredLevels: 9, storageKey: 'arcade.legacy.shape-sorter.v1', statePath: ['progress'], concepts: ['derivative shapes', 'numerator layout'], learned: 'How output and input dimensions determine derivative shape.', mistakes: 'Reversing rows and columns or collapsing vector derivatives.', nextConcept: 'Partial derivatives and frozen variables', achievement: 'Shape Master' },
  { id: 'partial-derivative-freeze', order: '02', title: 'Partial Derivative Freeze', description: 'Freeze independent inputs and trace active dependency paths.', difficulty: 'Foundation', icon: '❄', requiredLevels: 12, storageKey: 'arcade.legacy.partial-derivative-freeze.v1', statePath: ['learner', 'games', 'partialDerivativeFreeze', 'progress'], concepts: ['partial derivatives', 'dependency paths'], learned: 'What changes—and what stays fixed—inside a partial derivative.', mistakes: 'Deleting frozen multipliers or inventing undeclared dependencies.', nextConcept: 'Assembling scalar partials into Jacobians', achievement: 'Freeze Expert' },
  { id: 'build-jacobian', order: '03', title: 'Build the Jacobian', description: 'Place scalar sensitivities into the correct matrix cells.', difficulty: 'Intermediate', icon: 'J', requiredLevels: 14, storageKey: 'arcade.legacy.build-jacobian.v1', statePath: ['learner', 'games', 'buildTheJacobian', 'progress'], concepts: ['Jacobians', 'structural zeros'], learned: 'How each output row and input column locates a Jacobian entry.', mistakes: 'Transposition, misplaced entries, and confusing evaluated with structural zeros.', nextConcept: 'Recognizing dependency structure at a glance', achievement: 'Jacobian Builder' },
  { id: 'diagonal-detective', order: '04', title: 'Diagonal Detective', description: 'Trace dependency evidence and expose Jacobian structure.', difficulty: 'Intermediate', icon: '⌕', requiredLevels: 17, storageKey: 'arcade.legacy.diagonal-detective.v1', statePath: ['learner', 'games', 'diagonalDetective', 'progress'], concepts: ['diagonal Jacobians', 'sparsity'], learned: 'When independent lanes create diagonal, sparse, or dense Jacobians.', mistakes: 'Assuming every square Jacobian is diagonal or mistaking a zero value for no dependency.', nextConcept: 'Broadcasting one value across many lanes', achievement: 'Diagonal Detective' },
  { id: 'broadcast-factory', order: '05', title: 'Broadcast Factory', description: 'Compare broadcast, element-wise, reduction, and mixing operations.', difficulty: 'Intermediate', icon: '⇶', requiredLevels: 18, storageKey: 'arcade.legacy.broadcast-factory.v1', statePath: ['learner', 'games', 'broadcastFactory', 'progress'], concepts: ['broadcasting', 'shared parameters'], learned: 'Why a shared scalar creates repeated sensitivity lanes.', mistakes: 'Confusing broadcast operations with dot products, identity maps, or dense mixing.', nextConcept: 'Reductions from many lanes to one scalar', achievement: 'Broadcast Hero' },
  { id: 'reduction-relay', order: '06', title: 'Reduction Relay', description: 'Carry gradients through sums, means, dots, and losses.', difficulty: 'Advanced', icon: 'Σ', requiredLevels: 20, storageKey: 'arcade.legacy.reduction-relay.v1', statePath: ['learner', 'games', 'reductionRelay', 'progress'], concepts: ['reductions', 'gradient flow'], learned: 'How scalar reductions distribute sensitivity back across input lanes.', mistakes: 'Missing mean factors, stopping at an intermediate vector, or losing the upstream gradient.', nextConcept: 'Composing local derivatives along full circuits', achievement: 'Reduction Wizard' },
  { id: 'chain-rule-circuit', order: '07', title: 'Chain Rule Circuit', description: 'Multiply along routes and add between dependency paths.', difficulty: 'Advanced', icon: '⌁', requiredLevels: 22, storageKey: 'arcade.legacy.chain-rule-circuit.v1', statePath: ['learner', 'games', 'chainRuleCircuit', 'progress'], concepts: ['chain rule', 'gradient accumulation'], learned: 'How local derivatives compose through scalar and vector computation graphs.', mistakes: 'Adding serial factors, multiplying parallel paths, or reversing Jacobian order.', nextConcept: 'Synthesizing shape, sparsity, values, and order', achievement: 'Chain Rule Master' },
  { id: 'jacobian-tetris', order: '08', title: 'Jacobian Tetris', description: 'Assemble shape, structure, values, and chain order.', difficulty: 'Capstone', icon: '▦', requiredLevels: 12, storageKey: 'arcade.legacy.jacobian-tetris.v1', statePath: [], completedField: 'completed', scoreField: 'score', concepts: ['Jacobian synthesis', 'reverse mode'], learned: 'How derivative shape, dependency structure, values, and multiplication order fit together.', mistakes: 'Transpose errors, false dependencies, and incompatible chain blocks.', nextConcept: 'Activation gates in a trainable network', achievement: 'Jacobian Genius' },
  { id: 'relu-gatekeeper', order: 'III·1', chapter: 'Chapter III — Learning to Train a Network', title: 'ReLU Gatekeeper', description: 'Decide which activation gates transmit or stop the backward signal.', difficulty: 'Backpropagation', icon: '⌁', requiredLevels: 4, storageKey: 'arcade.training.relu-gatekeeper.v1', statePath: [], completedField: 'completedStages', concepts: ['ReLU derivatives', 'dead neurons'], learned: 'An activation function contributes a local Jacobian whose diagonal entries decide which gradient lanes survive.', mistakes: 'Confusing ReLU output with its derivative, or assuming a blocked gradient sets a weight to zero.', nextConcept: 'Using the gradient as an optimization direction', achievement: 'Gatekeeper' },
  { id: 'gradient-descent-navigator', order: 'III·2', chapter: 'Chapter III — Learning to Train a Network', title: 'Gradient Descent Navigator', description: 'Guide an optimizer through bowls, cliffs, plateaus, and ravines.', difficulty: 'Backpropagation', icon: '⌖', requiredLevels: 6, storageKey: 'arcade.training.gradient-descent-navigator.v1', statePath: [], completedField: 'completedLevels', concepts: ['gradient descent', 'learning rate'], learned: 'The gradient points uphill; subtracting a carefully scaled gradient moves parameters toward lower loss.', mistakes: 'Following the gradient uphill, treating a tiny gradient as convergence, or overshooting with a large learning rate.', nextConcept: 'Routing a complete backward pass through a network', achievement: 'Descent Navigator' },
  { id: 'backpropagation-boss', order: 'III·3', chapter: 'Chapter III — Learning to Train a Network', title: 'Backpropagation Boss Battle', description: 'Reconstruct a complete backward pass from local Jacobians.', difficulty: 'Finale', icon: '◆', requiredLevels: 4, storageKey: 'arcade.training.backpropagation-boss.v1', statePath: [], completedField: 'completedPhases', concepts: ['complete backpropagation', 'weight updates'], learned: 'Backpropagation is repeated Jacobian composition: route the incoming gradient through each local transformation, then update parameters.', mistakes: 'Skipping transpose gates, applying ReLU to the wrong value, or losing reduction and outer-product steps.', nextConcept: 'Exploring how gradients behave in deeper networks', achievement: 'Backprop Boss', finale: true },
];

export function gameById(id) { return GAME_DATA.find((game) => game.id === id); }
