import { LEVELS } from '../data/levels.js';
import { casesForLevel } from '../data/cases.js';
import { createEvidenceBoard } from '../components/evidence-board.js';
import { createJacobianGrid } from '../components/jacobian-grid.js';
import { createFeedbackPanel } from '../components/feedback-panel.js';
import { displayMath, inlineMath } from '../math-renderer.js';
import { explainDependency } from '../math/dependency-analysis.js';

const CLASS_LABELS={square:'Square',diagonal:'Diagonal',identity:'Identity',sparse:'Sparse',dense:'Dense',blockDiagonal:'Block diagonal',upperTriangular:'Upper triangular',lowerTriangular:'Lower triangular',permutationLike:'Permutation-like',zeroRow:'Contains a zero row',zeroColumn:'Contains a zero column'};
const ZERO_LABELS={'':'Choose a reason','no-dependency':'No dependency path','local-slope-zero':'Local slope zero','inactive-activation':'Inactive ReLU gate','identically-zero':'Derivative identically zero'};

function matrixLatex(matrix){return `\\begin{bmatrix}${matrix.map(row=>row.join('&')).join('\\\\')}\\end{bmatrix}`;}
function vectorLatex(item){return `\\mathbf{y}=\\begin{bmatrix}${item.outputs.map(output=>output.expressionLatex).join('\\\\')}\\end{bmatrix}`;}
function structuralLatex(item){return matrixLatex(item.dependencyMatrix.map(row=>row.map(value=>value?'\\bullet':'0')));}
function truthForClassification(item,key){if(key==='zeroRow')return item.classification.zeroRows.length>0;if(key==='zeroColumn')return item.classification.zeroColumns.length>0;return Boolean(item.classification[key]);}
function makeDefaultAnswer(item,persisted){return {shape:{rows:'',columns:''},dependencies:[],grid:{},classifications:[],derivatives:{},zeroReasons:{},...(persisted??{})};}

export function createGameView({item,rootState,game,engine,ui,onRefresh,onSelectLevel,onSelectCase,onGenerate,onNext}){
  const persisted=game.currentRound?.caseId===item.id?game.currentRound.answer:null;
  const answer=makeDefaultAnswer(item,persisted);
  const page=document.createElement('div');page.className='page';
  const header=document.createElement('div');header.className='page-heading';header.innerHTML=`<div><span class="kicker">Level ${item.level} · ${item.mode}</span><h1>${item.title}</h1><p>${LEVELS[item.level-1]?.objective??'Investigate the dependency structure.'}</p></div><div class="case-meta"><span class="badge info">Case ${item.id}</span><span class="badge">Seed ${item.seed}</span><span class="badge ${item.difficulty==='hard'?'warn':'good'}">${item.difficulty}</span></div>`;page.append(header);

  const levelNav=document.createElement('section');levelNav.className='card stack';levelNav.innerHTML=`<div class="spread"><div><strong>Case shelf</strong><p>Choose a level, a deterministic sample, or generate a seeded investigation.</p></div><button class="btn secondary small" data-action="generate">Generate case</button></div><div class="row"><label class="form-field">Level<select data-role="level-select">${LEVELS.map(level=>`<option value="${level.id}" ${level.id===item.level?'selected':''}>${level.id}. ${level.title}</option>`).join('')}</select></label><label class="form-field">Case<select data-role="case-select">${casesForLevel(item.level).map(candidate=>`<option value="${candidate.id}" ${candidate.id===item.id?'selected':''}>${candidate.title}</option>`).join('')}${item.mode==='generated'?`<option selected value="${item.id}">${item.title}</option>`:''}</select></label></div><div class="level-strip">${LEVELS.map(level=>`<button class="level-pill ${level.id===item.level?'current':''} ${game.progress.completedLevels.includes(level.id)?'complete':''}" data-level="${level.id}">${level.id}</button>`).join('')}</div>`;
  levelNav.querySelector('[data-action="generate"]').addEventListener('click',onGenerate);
  levelNav.querySelector('[data-role="level-select"]').addEventListener('change',event=>onSelectLevel(Number(event.target.value)));
  levelNav.querySelector('[data-role="case-select"]').addEventListener('change',event=>onSelectCase(event.target.value));
  levelNav.querySelectorAll('[data-level]').forEach(button=>button.addEventListener('click',()=>onSelectLevel(Number(button.dataset.level))));page.append(levelNav);

  const caseFile=document.createElement('section');caseFile.className='card case-file stack';caseFile.innerHTML=`<span class="kicker">Case file</span>${displayMath(vectorLatex(item),`Vector function with ${item.outputs.length} outputs`)}${item.intermediates.length?`<div class="intermediate-list"><strong>Intermediate clues</strong>${item.intermediates.map(node=>`<div>${inlineMath(`${node.name}=${node.expressionLatex}`)}</div>`).join('')}</div>`:''}${item.proposedBug?`<div class="callout error"><strong>Repair report:</strong> ${item.proposedBug.message}</div>`:''}<div class="callout"><strong>Convention:</strong> numerator layout. The Jacobian has one row per output and one column per input.</div>`;page.append(caseFile);

  const workspace=document.createElement('div');workspace.className='two-column';
  const mainStack=document.createElement('div');mainStack.className='stack';
  const shapeCard=document.createElement('section');shapeCard.className='card stack';shapeCard.innerHTML=`<span class="kicker">Step 1 · Shape</span><h2>Predict the evidence-grid dimensions</h2><div class="row"><label class="form-field">Output rows<input inputmode="numeric" min="1" max="4" data-shape="rows" value="${answer.shape.rows}"></label><span aria-hidden="true">×</span><label class="form-field">Input columns<input inputmode="numeric" min="1" max="4" data-shape="columns" value="${answer.shape.columns}"></label></div>`;
  shapeCard.querySelectorAll('[data-shape]').forEach(input=>input.addEventListener('input',event=>{answer.shape[event.target.dataset.shape]=event.target.value;mutate(false);}));mainStack.append(shapeCard);

  const wireCard=document.createElement('section');wireCard.className='card stack';wireCard.innerHTML=`<div class="spread"><div><span class="kicker">Step 2 · Evidence wires</span><h2>Who can influence whom?</h2></div><button class="btn secondary small" data-action="inspect-path" ${ui.selectedInput===null||ui.selectedOutput===null?'disabled':''}>Inspect selected path</button></div>`;
  wireCard.append(createEvidenceBoard({item,dependencies:answer.dependencies,selectedInput:ui.selectedInput,selectedOutput:ui.selectedOutput,reveal:ui.reveal,onSelectInput:index=>{ui.selectedInput=index;if(ui.selectedOutput!==null)toggleDependency(ui.selectedOutput,index);else onRefresh();},onSelectOutput:index=>{ui.selectedOutput=index;if(ui.selectedInput!==null)toggleDependency(index,ui.selectedInput);else onRefresh();},onSetDependency:(row,column,value)=>setDependency(row,column,value)}));
  const currentLinks=document.createElement('p');currentLinks.className='callout';currentLinks.setAttribute('aria-label','Text alternative for current dependency graph');currentLinks.textContent=answer.dependencies.length?`Current evidence list: ${answer.dependencies.map(key=>{const[r,c]=key.split('-').map(Number);return `${item.inputs[c].name} affects ${item.outputs[r].name}`;}).join('. ')}.`:'Current evidence list: no dependency wires have been drawn.';wireCard.append(currentLinks);
  if(ui.pathInspection){const path=document.createElement('div');path.className='callout warning';path.textContent=ui.pathInspection;wireCard.append(path);}
  wireCard.querySelector('[data-action="inspect-path"]').addEventListener('click',()=>{engine.useHint();ui.pathInspection=explainDependency(item.outputs[ui.selectedOutput].name,item.inputs[ui.selectedInput].name,item.graph);onRefresh();});mainStack.append(wireCard);

  const gridCard=document.createElement('section');gridCard.className='card stack';gridCard.innerHTML=`<div class="spread"><div><span class="kicker">Step 3 · Structural Jacobian</span><h2>Translate paths into cells</h2></div><button class="btn secondary small" data-action="transfer">Transfer my wires</button></div><div class="legend"><span><i>?</i> Unknown</span><span><i>●</i> May be nonzero</span><span><i>0</i> Structural zero</span>${item.evaluationPoint?'<span><i>0*</i> Path exists, value zero</span>':''}</div>`;
  gridCard.append(createJacobianGrid({item,grid:answer.grid,reveal:ui.reveal,onMark:(key,mark)=>{answer.grid[key]=mark;mutate();}}));gridCard.querySelector('[data-action="transfer"]').addEventListener('click',()=>{for(let r=0;r<item.expectedShape.rows;r+=1)for(let c=0;c<item.expectedShape.columns;c+=1)answer.grid[`${r}-${c}`]=answer.dependencies.includes(`${r}-${c}`)?'possible':'structural-zero';mutate();});mainStack.append(gridCard);

  workspace.append(mainStack);
  const sideStack=document.createElement('aside');sideStack.className='stack';
  const classification=document.createElement('section');classification.className='card stack';classification.innerHTML=`<span class="kicker">Step 4 · Classify</span><h2>Select every structure that applies</h2><div class="checkbox-grid">${item.classificationOptions.map(key=>`<label class="check-chip"><input type="checkbox" value="${key}" ${answer.classifications.includes(key)?'checked':''}>${CLASS_LABELS[key]}</label>`).join('')}</div><p class="matrix-caption">Sparse uses the game’s documented ≥⅓ structural-zero display threshold. Dense means fully connected.</p>`;classification.querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{answer.classifications=[...classification.querySelectorAll('input:checked')].map(node=>node.value);mutate(false);}));sideStack.append(classification);

  if(item.derivativeTargets.length){const derivativeCard=document.createElement('section');derivativeCard.className='card stack';derivativeCard.innerHTML='<span class="kicker">Step 5 · Confirm selected cells</span><h2>Calculate only what matters</h2>';item.derivativeTargets.forEach(target=>{const key=`${target.row}-${target.column}`;const field=document.createElement('label');field.className='form-field';field.innerHTML=`<span>${inlineMath(`\\partial ${item.outputs[target.row].name}/\\partial ${item.inputs[target.column].name}`)}</span><input data-derivative="${key}" value="${answer.derivatives[key]??''}" placeholder="Enter derivative expression" autocomplete="off">`;field.querySelector('input').addEventListener('input',event=>{answer.derivatives[key]=event.target.value;engine.saveDraft(answer);ui.result=null;});derivativeCard.append(field);});sideStack.append(derivativeCard);}

  if(item.evaluationPoint){const comparator=document.createElement('section');comparator.className='card stack';comparator.innerHTML=`<span class="kicker">Step 6 · Compare zero meanings</span><h2>Structural map vs evaluated Jacobian</h2><div class="callout"><strong>Evaluation point:</strong> ${Object.entries(item.evaluationPoint).map(([key,value])=>inlineMath(`${key}=${value}`)).join(', ')}</div><div class="two-panel"><p><strong>Structural question:</strong><br>Does a path exist?</p><p><strong>Numerical question:</strong><br>What is the local slope here?</p></div>`;for(const key of Object.keys(item.zeroReasons)){const[row,column]=key.split('-').map(Number);const label=document.createElement('label');label.className='form-field';label.innerHTML=`<span>Why is ${inlineMath(`J_{${row+1}${column+1}}`)} zero here?</span><select data-zero-reason="${key}">${Object.entries(ZERO_LABELS).map(([value,text])=>`<option value="${value}" ${answer.zeroReasons[key]===value?'selected':''}>${text}</option>`).join('')}</select>`;label.querySelector('select').addEventListener('change',event=>{answer.zeroReasons[key]=event.target.value;mutate(false);});comparator.append(label);}sideStack.append(comparator);}

  const actionCard=document.createElement('section');actionCard.className='card stack';actionCard.innerHTML=`<div class="row"><button class="btn accent" data-action="check">Check investigation</button><button class="btn secondary" data-action="hint">Clue ${Math.min((game.currentRound?.hintsUsed??0)+1,item.hints.length)}</button><button class="btn secondary" data-action="reveal">Reveal case</button></div><div data-role="hint"></div>`;
  actionCard.querySelector('[data-action="check"]').addEventListener('click',()=>ui.onCheck(answer));
  actionCard.querySelector('[data-action="hint"]').addEventListener('click',()=>{const count=engine.useHint();const hint=item.hints[Math.min(count-1,item.hints.length-1)]??'Inspect the computation paths one output at a time.';ui.hint=hint;onRefresh();});
  actionCard.querySelector('[data-action="reveal"]').addEventListener('click',()=>{ui.reveal=true;answer.shape={rows:String(item.expectedShape.rows),columns:String(item.expectedShape.columns)};answer.dependencies=[];item.dependencyMatrix.forEach((row,r)=>row.forEach((depends,c)=>{if(depends)answer.dependencies.push(`${r}-${c}`);}));for(let r=0;r<item.expectedShape.rows;r+=1)for(let c=0;c<item.expectedShape.columns;c+=1){const key=`${r}-${c}`;answer.grid[key]=item.dependencyMatrix[r][c]?((item.zeroReasons[key]==='local-slope-zero'||item.zeroReasons[key]==='inactive-activation')?'evaluated-zero':'possible'):'structural-zero';}answer.classifications=item.classificationOptions.filter(key=>truthForClassification(item,key));item.derivativeTargets.forEach(target=>answer.derivatives[`${target.row}-${target.column}`]=target.expected[0]);answer.zeroReasons={...item.zeroReasons};engine.saveDraft(answer);onRefresh();});
  if(ui.hint){const hint=actionCard.querySelector('[data-role="hint"]');hint.className='callout hint-card';hint.textContent=ui.hint;}sideStack.append(actionCard);
  workspace.append(sideStack);page.append(workspace);

  if(ui.result&&ui.score){page.append(createFeedbackPanel(item,ui.result,ui.score));}
  if(ui.reveal||ui.result?.allCorrect){const reveal=document.createElement('section');reveal.className='card stack';const classifications=item.classificationOptions.filter(key=>truthForClassification(item,key));reveal.innerHTML=`<span class="kicker">Complete evidence report</span><h2>Structure first, values second</h2><div class="three-column"><div><h3>Dependency pattern</h3>${displayMath(structuralLatex(item))}</div><div><h3>Symbolic Jacobian</h3>${displayMath(matrixLatex(item.expectedJacobian))}</div>${item.evaluatedJacobian?`<div><h3>Evaluated Jacobian</h3>${displayMath(matrixLatex(item.evaluatedJacobian))}</div>`:'<div><h3>Evaluation</h3><p>No point evaluation is required in this case.</p></div>'}</div><div class="classification-result">${classifications.map(key=>`<span class="badge good">${CLASS_LABELS[key]}</span>`).join('')}</div><div class="callout"><strong>Dependency matrix ≠ Jacobian:</strong> bullets record where derivatives may be nonzero; the symbolic matrix contains the actual derivative expressions.</div><p>${item.explanation}</p><button class="btn accent" data-action="next">Next case</button>`;reveal.querySelector('[data-action="next"]').addEventListener('click',onNext);page.append(reveal);}

  function mutate(refresh=true){engine.saveDraft(answer);ui.result=null;ui.score=null;ui.reveal=false;if(refresh)onRefresh();}
  function setDependency(row,column,value){const key=`${row}-${column}`;const set=new Set(answer.dependencies);if(value)set.add(key);else set.delete(key);answer.dependencies=[...set].sort();mutate();}
  function toggleDependency(row,column){const key=`${row}-${column}`;setDependency(row,column,!answer.dependencies.includes(key));}
  return page;
}
