import { masteryPercentage, mostFrequentMisconception } from '../engine/mastery.js';
import { MISCONCEPTIONS } from '../data/misconceptions.js';

export function createProgressView({rootState,game,onExport,onImport,onReset,onOpenLevel}){
  const page=document.createElement('div');page.className='page';const mastery=masteryPercentage(game.mastery);const frequent=mostFrequentMisconception(game.mastery);
  page.innerHTML=`<div class="page-heading"><div><span class="kicker">Progress dashboard</span><h1>Investigation record</h1><p>Reasoning mastery, misconceptions, persistence controls, and recommended review.</p></div><span class="badge good">${mastery}% overall mastery</span></div>
  <div class="three-column"><section class="card metric"><small>Completed cases</small><strong>${game.progress.completedCases.length}</strong></section><section class="card metric"><small>Best streak</small><strong>${game.progress.bestStreak}</strong></section><section class="card metric"><small>Total score</small><strong>${game.progress.score}</strong></section></div>
  <section class="card stack"><h2>Mastery by concept</h2><div class="jacobian-wrap"><table class="mastery-table"><thead><tr><th>Concept</th><th>Attempts</th><th>Accuracy</th><th>Hints</th><th>State</th></tr></thead><tbody>${Object.entries(game.mastery).map(([key,item])=>`<tr><td>${key}</td><td>${item.attempts}</td><td>${item.attempts?Math.round(100*item.correct/item.attempts):0}%</td><td>${item.hintsUsed}</td><td class="mastery-state">${item.masteryState}</td></tr>`).join('')||'<tr><td colspan="5">Solve a case to begin tracking mastery.</td></tr>'}</tbody></table></div></section>
  <section class="card stack"><h2>Recommended review</h2><div class="callout warning">${frequent?MISCONCEPTIONS[frequent]:'No repeated misconception has been detected yet. Continue with the next unlocked case.'}</div><button class="btn secondary" data-action="review">Open level ${Math.max(1,game.progress.currentLevel-1)} review</button></section>
  <section class="card stack"><h2>Progress portability</h2><p>Export creates a versioned JSON file. Import validates the schema and rejects malformed state.</p><div class="row"><button class="btn secondary" data-action="export">Export progress</button><label class="btn secondary" for="import-progress">Import progress</label><input class="sr-only" id="import-progress" type="file" accept="application/json"><button class="btn danger" data-action="reset">Reset progress</button></div></section>`;
  page.querySelector('[data-action="export"]').addEventListener('click',onExport);page.querySelector('#import-progress').addEventListener('change',event=>onImport(event.target.files?.[0]));page.querySelector('[data-action="reset"]').addEventListener('click',onReset);page.querySelector('[data-action="review"]').addEventListener('click',()=>onOpenLevel(Math.max(1,game.progress.currentLevel-1)));
  return page;
}
